export const fieldMap = () => [
  {
    field_name: "Tax Year",
    field_tool: "Tax Year",
    field_db: "application_tax_year",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Applicant",
    field_tool: "Applicant",
    field_db: "applicant_residency_other",
    type: "Button",
    notes: "Default to 'no'?",
  },
  {
    field_name: "ApplicantName",
    field_tool: "Applicant_Name",
    field_db: "applicant_name",
    type: "Text",
    notes: "",
  },
  {
    field_name: "CoapplicantSpouseName",
    field_tool: "Co-applicant/Spouse_Name",
    field_db: "coapplicant_name",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "ApplicantSocial Security",
    field_tool: "Applicant_*Social Security #",
    field_db: null, //unused due to compliance
    type: "Text",
    notes: "N/A",
  },
  {
    field_name: "CoapplicantSpouseSocial Security",
    field_tool: "Co-applicant/Spouse_*Social Security #",
    field_db: null, //unused due to compliance
    type: "Text",
    notes: "N/A",
  },
  {
    field_name: "ApplicantImmigration",
    field_tool: "Applicant_Immigration #",
    field_db: "applicant_alien",
    type: "Text",
    notes: "",
  },
  {
    field_name: "CoapplicantSpouseImmigration",
    field_tool: "Co-applicant/Spouse_Immigration #",
    field_db: "coapplicant_alien",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "ApplicantDate of birth",
    field_tool: "Applicant_Date of birth",
    field_db: "applicant_date_of_birth",
    type: "Text",
    notes: "",
  },
  {
    field_name: "CoapplicantSpouseDate of birth",
    field_tool: "Co-applicant/Spouse_Date of birth",
    field_db: "coapplicant_date_of_birth",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "Applicant of ownership",
    field_tool: "Applicant_% of ownership",
    field_db: "",
    type: "Text",
    notes: "",
  },
  {
    field_name: "CoapplicantSpouse of ownership",
    field_tool: "Co-applicant/Spouse_% of ownership",
    field_db: "",
    type: "Text",
    notes: "",
  },
  {
    field_name: "ApplicantDate of permanent residency",
    field_tool: "Applicant_Date of permanent residency",
    field_db: "applicant_residency",
    type: "Text",
    notes: "",
  },
  {
    field_name: "CoapplicantSpouseDate of permanent residency",
    field_tool: "Co-applicant/Spouse_Date of permanent residency",
    field_db: "coapplicant_residency",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "Homestead address",
    field_tool: "Homestead address",
    field_db: "application_911_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Mailing address if different",
    field_tool: "Mailing address, if different",
    field_db: "applicant_mail_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Parcel identification number or legal description",
    field_tool: "Parcel identification number or legal description",
    field_db: "application_parcel",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Type of deed",
    field_tool: "Type of deed",
    field_db: "application_deed_type",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Date of deed",
    field_tool: "Date of deed",
    field_db: "application_sale_date",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Type of deed Date of deed",
    field_tool: "Type of deed Date of deed",
    field_db: "",
    type: "Text",
    notes: "concatinate application_deed_type and application_sale_date",
  },
  {
    field_name: "Book",
    field_tool: "Book",
    field_db: "application_book",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Page",
    field_tool: "Page",
    field_db: "application_page",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Date",
    field_tool: "Date",
    field_db: null, //NOTE we are not pulling this out of the database in v1
    type: "Text",
    notes: "",
  },
  {
    field_name: "or Instrument number",
    field_tool: "or Instrument number",
    field_db: "",
    type: "Text",
    notes: "",
  },
  {
    field_name: "undefined_5",
    field_tool: "undefined",
    field_db: "applicant_previous_homestead",
    type: "Button",
    notes: "Did any applicant receive or file for exemptions last year? 1 value",
  },
  {
    field_name: "undefined_6",
    field_tool: "undefined",
    field_db: "applicant_previous_homestead",
    type: "Button",
    notes: "Did any applicant receive or file for exemptions last year? 0 value",
    fn: (e) => {
      if (!e && e !== "0") {
        return 1;
      } else {
        return 0;
      }
    },
  },
  {
    field_name: "Previous address",
    field_tool: "Previous address:",
    field_db: "applicant_previous_homestead_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "date_2",
    field_tool: "date",
    field_db: null,
    type: "Text",
    notes: "Previous residency outside Florida and date terminated (coapplicant)",
  },
  {
    field_name: "dateEvidence of relinquishing driver license from other state",
    field_tool: "date_Evidence of relinquishing driver license from other state",
    field_db: null,
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateEvidence of relinquishing driver license from other state_2",
    field_tool: "date_Evidence of relinquishing driver license from other state",
    field_db: null,
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateFlorida vehicle tag number",
    field_tool: "date_Florida vehicle tag number",
    field_db: "applicant_vehicle_tag",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateFlorida vehicle tag number_2",
    field_tool: "date_Florida vehicle tag number",
    field_db: "coapplicant_vehicle_tag",
    type: "Text",
    notes: "",
  },
  {
    field_name: "date_3",
    field_tool: "date",
    field_db: "",
    type: "Text",
    notes: "Florida voter registration number (if US citizen) (coapplicant)",
  },
  {
    field_name: "dateCurrent employer",
    field_tool: "date_Current employer",
    field_db: "applicant_employer",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateCurrent employer_2",
    field_tool: "date_Current employer",
    field_db: "coapplicant_employer",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "dateAddress on your last IRS return",
    field_tool: "date_Address on your last IRS return",
    field_db: "applicant_irs_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateAddress on your last IRS return_2",
    field_tool: "date_Address on your last IRS return",
    field_db: "coapplicant_irs_address",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "dateSchool location of dependent children",
    field_tool: "date_School location of dependent children",
    field_db: "applicant_school",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateSchool location of dependent children_2",
    field_tool: "date_School location of dependent children",
    field_db: "coapplicant_school",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateBank statement and checking account mailing address",
    field_tool: "date_Bank statement and checking account mailing address",
    field_db: "applicant_bank_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "dateBank statement and checking account mailing address_2",
    field_tool: "date_Bank statement and checking account mailing address",
    field_db: "applicant_bank_address",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "undefined_7",
    field_tool: "undefined",
    field_db: null,
    type: "Button",
    notes: "1 value",
  },
  {
    field_name: "undefined_8",
    field_tool: "undefined",
    field_db: null,
    type: "Button",
    notes: "0 value",
  },
  {
    field_name: "undefined_9",
    field_tool: "undefined",
    field_db: null,
    type: "Button",
    notes: "1 value where coapplicant = 1",
  },
  {
    field_name: "undefined_10",
    field_tool: "undefined",
    field_db: null,
    type: "Button",
    notes: "0 value where coapplicant = 0",
  },
  {
    field_name: "Name and address of any owners not residing on the property",
    field_tool: "Name and address of any owners not residing on the property",
    field_db: "applicant_other_owners_address",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Age 65 and older with limited income amount determined by ordinance",
    field_tool: "Age 65 and older with limited income (amount determined by ordinance",
    field_db: "applicant_other_exemptions_1",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Age 65 and older with limited income and permanent residency for 25 years or more",
    field_tool: "Age 65 and older with limited income and permanent residency for 25 years or more",
    field_db: "applicant_other_exemptions_2",
    type: "Button",
    notes: "",
  },
  {
    field_name: "5000 widowed",
    field_tool: "5,000 widowed",
    field_db: "applicant_other_exemptions_3",
    type: "Button",
    notes: "",
  },
  {
    field_name: "5000 blind",
    field_tool: "5,000 blind",
    field_db: "applicant_other_exemptions_4",
    type: "Button",
    notes: "",
  },
  {
    field_name: "5000 totally and permanently disabled",
    field_tool: "5,000 totally and permanently disabled",
    field_db: "applicant_other_exemptions_5",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Total and permanent disability quadriplegic",
    field_tool: "Total and permanent disability -quadriplegic",
    field_db: "applicant_other_exemptions_6",
    type: "Button",
    notes: "",
  },
  {
    field_name:
      "Certain total and permanent disabilities limited income and hemiplegic paraplegic wheelchair required",
    field_tool:
      "Certain total and permanent disabilities -limited income and hemiplegic, paraplegic, wheelchair required",
    field_db: "applicant_other_exemptions_7",
    type: "Button",
    notes: "",
  },
  {
    field_name:
      "First responder totally and permanently disabled in the line of duty or surviving spouse",
    field_tool:
      "First responder totally and permanently disabled in the line of duty or surviving spouse",
    field_db: "applicant_other_exemptions_8",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Surviving spouse of first responder who died in the line of duty",
    field_tool: "Surviving spouse of first responder who died in the line of duty",
    field_db: "applicant_other_exemptions_9",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Disabled veteran discount 65 or older which carries over to the surviving spouse",
    field_tool: "Disabled veteran discount, 65 or older which carries over to the surviving spouse",
    field_db: "applicant_other_exemptions_10",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Veteran disabled 10 or more",
    field_tool: "Veteran disabled 10% or more",
    field_db: "applicant_other_exemptions_11",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Disabled veteran confined to wheelchair serviceconnected",
    field_tool: "Disabled veteran confined to wheelchair, service-connected",
    field_db: "applicant_other_exemptions_12",
    type: "Button",
    notes: "",
  },
  {
    field_name:
      "Serviceconnected totally and permanently disabled veteran or veterans surviving spouse Applicants for",
    field_tool:
      "Service-connected totally and permanently disabled veteran or veteran’s surviving spouse. Applicants for",
    field_db: "applicant_other_exemptions_13",
    type: "Button",
    notes: "",
  },
  {
    field_name:
      "Surviving spouse of veteran who died while on active duty Applicants for this exemption qualify for a",
    field_tool:
      "Surviving spouse of veteran who died while on active duty. Applicants for this exemption qualify for a",
    field_db: "applicant_other_exemptions_14",
    type: "Button",
    notes: "",
  },
  {
    field_name: "Other specify",
    field_tool: "Other, specify",
    field_db: "applicant_other_benefits",
    type: "Button",
    notes: "",
  },

  {
    field_name: "Parcel number",
    field_tool: "Parcel number",
    field_db: "",
    type: "Text",
    notes: "On Exemptions Page (service connected totally…)",
  },
  {
    field_name: "Parcel number_2",
    field_tool: "Parcel number",
    field_db: "",
    type: "Text",
    notes: "On Exemptions Page (surviving spouse…)",
  },
  {
    field_name: "undefined_11",
    field_tool: "undefined",
    field_db: null,
    type: "Text",
    notes: "On Exemptions Page (other specify)",
  },
  {
    field_name: "Date_2",
    field_tool: "Date",
    field_db: "applicant_created",
    type: "Text",
    notes: "appplicant signature date",
    fn: (e) => {
      if (!e) return null;
      try {
        const date = new Date(e);
        return date.toISOString().split("T")[0];
      } catch (error) {
        console.log({ error });
        return null;
      }
    },
  },
  {
    field_name: "Date_3",
    field_tool: "Date",
    field_db: "coapplicant_created",
    type: "Text",
    notes: "coapplicant signature date",
    fn: (e) => {
      if (!e) return null;
      try {
        const date = new Date(e);
        return date.toISOString().split("T")[0];
      } catch (error) {
        console.log({ error });
        return null;
      }
    },
  },
  {
    field_name: "County Combo Box4",
    field_tool: "Select County",
    field_db: "",
    type: "Choice",
    notes: "Putnam'",
  },
  {
    field_name: "Applicant Phone Coapplicant Phone",
    field_tool: "Applicant Phone Co-applicant Phone",
    field_db: "applicant_phone",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Co-Applicant Phone Coapplicant Phone",
    field_tool: "Applicant Phone Co-applicant Phone",
    field_db: "coapplicant_phone",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "County Combo Box5",
    field_tool: "Select County",
    field_db: "",
    type: "Choice",
    notes: "N/A",
  },
  {
    field_name: "County Combo Box6",
    field_tool: "Select County",
    field_db: "",
    type: "Choice",
    notes: "N/A",
  },
  {
    field_name: "date",
    field_tool: "date",
    field_db: "",
    type: "Text",
    notes: "Previous residency outside Florida and date terminated ",
  },
  {
    field_name: "date3",
    field_tool: "date",
    field_db: "",
    type: "Text",
    notes: "FL driver license or ID card number",
  },
  {
    field_name: "date4",
    field_tool: "date",
    field_db: "",
    type: "Text",
    notes: "FL driver license or ID card number (coapplicant)",
  },
  {
    field_name: "date5",
    field_tool: "date",
    field_db: "",
    type: "Text",
    notes: "Florida voter registration number (if US citizen) ",
  },
  {
    field_name: "date6",
    field_tool: "date",
    field_db: "applicant_domicile",
    type: "Text",
    notes: "",
  },
  {
    field_name: "date7",
    field_tool: "date",
    field_db: "applicant_domicile",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "Signature1",
    field_tool: "N/A",
    field_db: "applicant_signature",
    type: "Signature",
    notes: "",
  },
  {
    field_name: "Signature2",
    field_tool: "N/A",
    field_db: "coapplicant_signature",
    type: "Signature",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "Text a",
    field_tool: "N/A",
    field_db: "",
    type: "Text",
    notes: "Previous residency outside Florida and date terminated",
  },
  {
    field_name: "Text b",
    field_tool: "N/A",
    field_db: "applicant_driver_license",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Text e",
    field_tool: "N/A",
    field_db: "applicant_voter",
    type: "Text",
    notes: "",
  },
  {
    field_name: "Text f",
    field_tool: "N/A",
    field_db: "",
    type: "Text",
    notes: "Declaration of Domicile (text)",
  },
  {
    field_name: "Text g",
    field_tool: "N/A",
    field_db: "applicant_voter",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
  {
    field_name: "Text h",
    field_tool: "N/A",
    field_db: "",
    type: "Text",
    notes: "Declaration of Domicile (text) (coapplicant)",
  },
  {
    field_name: "homestead exemption",
    field_tool: "New",
    field_db: null, //NOTE default checked as new,
    type: "Button",
    notes: "What's the logic?",
  },
  {
    field_name: "marital status",
    field_tool: "undefined",
    field_db: "applicant_marital",
    type: "Button",
    notes: "Reach out to Malcolm for domain",
  },
  {
    field_name: "Text c",
    field_tool: "N/A",
    field_db: "",
    type: "Text",
    notes: "Previous residency outside Florida and date terminated (coapplicant)",
  },
  {
    field_name: "Text d",
    field_tool: "N/A",
    field_db: "applicant_driver_license",
    type: "Text",
    notes: "where applicant_coapp = 1",
  },
];
